2024-08-08 23:56:23,075 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/home/deep/PycharmProjects/homework2/modul12/test_12_4.py", line 22, in test_run
    runner = Runner(name=123, speed=10)
  File "/home/deep/PycharmProjects/homework2/modul12/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-08-08 23:56:23,077 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/home/deep/PycharmProjects/homework2/modul12/test_12_4.py", line 9, in test_walk
    runner = Runner(name="Алиса", speed=-10)
  File "/home/deep/PycharmProjects/homework2/modul12/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
